default:
    image: python:latest

stages:
    - test
    - vm_deploy
    - heroku_deploy

tester:
    stage: test
    script:
        - | 
            pip install --upgrade pip && pip install -r requirements.txt
            python -m unittest discover
    allow_failure: false

heroku_deployer:
    stage: heroku_deploy
    image: ceorcham/dpl-heroku
    script: 
        - dpl --provider=heroku --app=exercisingapp --api-key="$API_KEY"