default:
    image: python:latest

stages:
    - test
    - vm_deploy
    - heroku_deploy

tester:
    stage: test
    script:
        - | 
            pip install -r requirements.txt
            python -m unittest discover
    allow_failure: false

vm_deployer:
    stage: vm_deploy
    script:
        - | 
            export PORT=5000
            python exerciseapp/app.py </dev/null &>/dev/null &

heroku_deployer:
    stage: heroku_deploy
    image: ceorcham/dpl-heroku
    script: 
        - dpl --provider=heroku --app=exercisingapp --api-key="$API_KEY"